# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DeutschTui < Formula
  desc "A terminal-native German flashcard and quiz app."
  homepage "https://github.com/tungnguyenlam/language-learning-tui"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tungnguyenlam/language-learning-tui/releases/download/v0.4.0/deutsch-tui-macos-amd64"
      sha256 "ccb78c09e116502eeebb5b286ee63987c8a79e098734f63b48ac263a3ee0b9a2"

      define_method(:install) do
        bin.install "deutsch-tui-macos-amd64" => "deutsch-tui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tungnguyenlam/language-learning-tui/releases/download/v0.4.0/deutsch-tui-macos-arm64"
      sha256 "c9a8aef7ff0b9d4f7d90ebbeadb807efe37adeb06578b911c13e5ab50c2f7806"

      define_method(:install) do
        bin.install "deutsch-tui-macos-arm64" => "deutsch-tui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/tungnguyenlam/language-learning-tui/releases/download/v0.4.0/deutsch-tui-linux-amd64"
      sha256 "acff61cece99610f938031dffc1921e04ba992f940c7a61c09dd6a25d19eb422"
      define_method(:install) do
        bin.install "deutsch-tui-linux-amd64" => "deutsch-tui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tungnguyenlam/language-learning-tui/releases/download/v0.4.0/deutsch-tui-linux-arm64"
      sha256 "9b97b8f2a8392b41e53454a59a146b0f1b410faa98731d99720929aaa4b1dded"
      define_method(:install) do
        bin.install "deutsch-tui-linux-arm64" => "deutsch-tui"
      end
    end
  end
end
